clear;
original = imread('C:\Users\Manuel\Documents\MATLAB\images\artificiales\mitad_mitad_250x250.png');
[m, n] = size(original);
image_array = zeros(m, n, 'single');
image_array(:,:) = single(original);
flat_array = image_array(:);
[X,Y] = meshgrid(1:size(image_array,1), 1:size(image_array,2));
flat_array(:,2) = Y(:);
flat_array(:,3) = X(:);    
flat_array = normalize_array(flat_array);
[center, U, obj_fcn] = fcm_picked_center(flat_array, 2, [2.0, 4, 1e-5,1], [-0.7071,-0.7071,-0.7071;0.7071,0.7071,0.7071]);
figure;
to_plot = reshape(U(1, :), n, m);
imagesc(to_plot), colorbar;
truesize;
figure;
to_plot = reshape(U(2, :), n, m);
imagesc(to_plot), colorbar;
truesize;
